apiVersion: v1
kind: ServiceAccount
metadata:
  name: cryptoprices-operator
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptoprices-operator
  labels:
    app: cryptoprices-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cryptoprices-operator
  template:
    metadata:
      labels:
        app: cryptoprices-operator
    spec:
      serviceAccountName: cryptoprices-operator
      containers:
      - name: cryptoprices-operator
        image: ghcr.io/timrcase/cryptoprices-operator:v1.1
        imagePullPolicy: IfNotPresent
        env:
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            configMapKeyRef:
              name: slack-config
              key: webhook_url
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cryptoprices-operator
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create, patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["watch", "create"]
- apiGroups: ["operators.timrcase.github.io"]
  resources: ["cryptoprices"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cryptoprices-operator
subjects:
- kind: ServiceAccount
  name: cryptoprices-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: cryptoprices-operator
  apiGroup: rbac.authorization.k8s.io
